<a href="https://colab.research.google.com/github/YuCheLiu/machine_learning/blob/main/Data_Preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [5]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer, make_column_selector

%matplotlib

Using matplotlib backend: agg


In [7]:
df = pd.read_csv("Customer-Churn.csv")
df.head()

gender  SeniorCitizen Partner  ... MonthlyCharges  TotalCharges Churn
0  Female              0     Yes  ...          29.85         29.85    No
1    Male              0      No  ...          56.95       1889.50    No
2    Male              0      No  ...          53.85        108.15   Yes
3    Male              0      No  ...          42.30       1840.75    No
4  Female              0      No  ...          70.70        151.65   Yes

[5 rows x 20 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gender            7043 non-null   object 
 1   SeniorCitizen     7043 non-null   int64  
 2   Partner           7043 non-null   object 
 3   Dependents        7043 non-null   object 
 4   tenure            7043 non-null   int64  
 5   PhoneService      7043 non-null   object 
 6   MultipleLines     7043 non-null   object 
 7   InternetService   7043 non-null   object 
 8   OnlineSecurity    7043 non-null   object 
 9   OnlineBackup      7043 non-null   object 
 10  DeviceProtection  7043 non-null   object 
 11  TechSupport       7043 non-null   object 
 12  StreamingTV       7043 non-null   object 
 13  StreamingMovies   7043 non-null   object 
 14  Contract          7043 non-null   object 
 15  PaperlessBilling  7043 non-null   object 
 16  PaymentMethod     7043 non-null   object 


In [10]:
df.isnull().sum()

gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [11]:
imputer = SimpleImputer()
new_TC = imputer.fit_transform(df[['TotalCharges']])
df['TotalCharges'] = new_TC

In [12]:
df['TotalCharges'].isnull().sum()

0

In [16]:
cat_var = df[['StreamingMovies', 'Contract','PaperlessBilling','PaymentMethod']]
cat_var.head()

StreamingMovies        Contract PaperlessBilling              PaymentMethod
0              No  Month-to-month              Yes           Electronic check
1              No        One year               No               Mailed check
2              No  Month-to-month              Yes               Mailed check
3              No        One year               No  Bank transfer (automatic)
4              No  Month-to-month              Yes           Electronic check

In [17]:
encoder = OneHotEncoder(drop = 'first')
encoded_var = encoder.fit_transform(cat_var)

In [19]:
print("Encoded matrix \n", encoded_var.toarray(),"\n")
print("Encoded columns name \n", encoder.get_feature_names(),"\n")
print("Encoded catgorical dataframe")
pd.DataFrame(encoded_var.toarray(), columns=encoder.get_feature_names())

Encoded matrix 
 [[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]] 

Encoded columns name 
 ['x0_No internet service' 'x0_Yes' 'x1_One year' 'x1_Two year' 'x2_Yes'
 'x3_Credit card (automatic)' 'x3_Electronic check' 'x3_Mailed check'] 

Encoded catgorical dataframe


x0_No internet service  x0_Yes  ...  x3_Electronic check  x3_Mailed check
0                        0.0     0.0  ...                  1.0              0.0
1                        0.0     0.0  ...                  0.0              1.0
2                        0.0     0.0  ...                  0.0              1.0
3                        0.0     0.0  ...                  0.0              0.0
4                        0.0     0.0  ...                  1.0              0.0
...                      ...     ...  ...                  ...              ...
7038                     0.0     1.0  ...                  0.0              1.0
7039                     0.0     1.0  ...                  0.0              0.0
7040                     0.0     0.0  ...                  1.0              0.0
7041                     0.0     0.0  ...                  0.0              1.0
7042                     0.0     1.0  ...                  0.0              0.0

[7043 rows x 8 columns]

In [20]:
num_var = df[['MonthlyCharges','TotalCharges']]
num_var.head()

MonthlyCharges  TotalCharges
0           29.85         29.85
1           56.95       1889.50
2           53.85        108.15
3           42.30       1840.75
4           70.70        151.65

In [21]:
scaler = StandardScaler()

scaled_var = scaler.fit_transform(num_var)

print(scaled_var)

[[-1.16032292 -0.99497138]
 [-0.25962894 -0.17387565]
 [-0.36266036 -0.96039939]
 ...
 [-1.1686319  -0.85518222]
 [ 0.32033821 -0.87277729]
 [ 1.35896134  2.01391739]]


In [22]:
features = df.drop(columns='Churn')
features.head()

gender  SeniorCitizen  ... MonthlyCharges TotalCharges
0  Female              0  ...          29.85        29.85
1    Male              0  ...          56.95      1889.50
2    Male              0  ...          53.85       108.15
3    Male              0  ...          42.30      1840.75
4  Female              0  ...          70.70       151.65

[5 rows x 19 columns]

In [23]:
preprocessor = ColumnTransformer([('scaler', scaler, make_column_selector(dtype_include='number')),('encoder',encoder,make_column_selector(dtype_include='object'))])
processed_feat = preprocessor.fit_transform(features)

print(processed_feat)
print(processed_feat.shape)

[[-0.43991649 -1.27744458 -1.16032292 ...  0.          1.
   0.        ]
 [-0.43991649  0.06632742 -0.25962894 ...  0.          0.
   1.        ]
 [-0.43991649 -1.23672422 -0.36266036 ...  0.          0.
   1.        ]
 ...
 [-0.43991649 -0.87024095 -1.1686319  ...  0.          1.
   0.        ]
 [ 2.27315869 -1.15528349  0.32033821 ...  0.          0.
   1.        ]
 [-0.43991649  1.36937906  1.35896134 ...  0.          0.
   0.        ]]
(7043, 30)
